perawallet/pera-ios

.github/workflows/cla.yml
CLA assistant created and added to repo
=> CLA assistant created

Classes/Accounts/Detail/Assets/List/Screens/AccountAssetListAPIDataController.swift, Classes/Accounts/Detail/Assets/List/Screens/AccountAssetListLayout.swift, Classes/Accounts/Detail/Assets/List/Screens/AccountAssetListViewController.swift, Classes/Shared/List/Primary/ListItemView/CollectibleAsset/CollectibleListItemCell.swift, Classes/Shared/List/Primary/ListItemView/CollectibleAsset/CollectibleListItemView.swift, Classes/Shared/List/Primary/ListItemView/CollectibleAsset/CollectibleListItemViewTheme.swift, algorand.xcodeproj/project.pbxproj
- Fixed issue with NFT rows. They will now calculate their height properly.
- Fixed issue with sorting. Assets will now be sorted based on the selected sorting option when the user enters the assets screen.
- Fixed issue with background color on the assets list screen. The background will no longer be plain black or white.
=> [IOS] - Bug - Account Details Page - Assets get shuffled around when scrolling through the list

Classes/Transactions/Send/Inbox/SendAssetInboxScreen.swift, algorand.xcodeproj/project.pbxproj
- Fixed the reported issue. The "Sign with Ledger" modal/overlay will now be dismissed after the last transaction is signed.
=> [ARC59] - iOS - Transfer Between Accounts - Ledger More Transaction Issue

Classes/Analytics/Core/ALGAnalyticsEvent.swift, Classes/Analytics/Events/OnboardCreateAccountEvent.swift, Classes/Authentication/Introduction/Recover/RecoverAccountViewController.swift
New analytics events added: recover with Algo25 and recover with One Key
=> [HD Wallets] Event Tracking

Classes/Accounts/Detail/Assets/List/Screens/AccountAssetListAPIDataController.swift, Classes/Accounts/Detail/Assets/List/Views/AccountNotBackedUpWarningItem/AccountDetailAccountNotBackedUpWarningCell.swift, Classes/Models/Accounts/Account/Response/Account.swift, algorand.xcodeproj/project.pbxproj
The backup warning is presented to the user just for accounts with balance.
=> :bug: only show backup warning if balance is positive

Classes/Models/Application/User/User.swift
Remove wallet from keychain if deleted account was the last account for that wallet. Fix wallet name generation
=> 1834 delete hd account wallet

Classes/AlgorandSecureBackup/AlgorandSecureBackupFlowCoordinator.swift, Classes/AlgorandSecureBackup/Instructions/AlgorandSecureBackupInstructionsScreen.swift, Resources/Localization/en.lproj/Localizable.strings, algorand.xcodeproj/project.pbxproj
- Warning to ASB to show Ledger and HD wallets not supported added. 
- Accounts list to backup filtered to not include hd or ledger accounts
=> [iOS] Add warning to ASB to show Ledger and HD wallets not supported

Classes/Accounts/Detail/AccountInformation/LedgerAccountInformation/LedgerAccountInformationScreen.swift, Classes/Accounts/Detail/AccountInformation/RekeyedAccountInformation/RekeyedAccountInformationScreen.swift, Classes/Accounts/Detail/AccountInformation/Shared/Views/AccountInformationOptionsView/AccountInformationOptionItemViewModel.swift, Classes/Accounts/Detail/AccountInformation/StandardAccountInformation/StandardAccountInformationScreen.swift, Classes/Accounts/Detail/Main/Screens/AccountDetailViewController.swift, Classes/Accounts/Detail/Main/Screens/AccountInformationFlowCoordinator.swift, Classes/Accounts/Options/List/Screens/OptionsViewController.swift, Classes/Demo/RescanAccountsListItemViewModel.swift, Classes/Demo/RescanRekeyedAccountsCoordinator.swift, Classes/Models/Accounts/Account/Response/Account+Helpers.swift, Classes/Routing/Router.swift, Classes/Routing/Screen.swift, Classes/Shared/LoadingIndicators/ScreenLoadingIndicator/ScreenLoadingIndicator.swift, Extensions/Font+CustomFonts.swift, Resources/Localization/Localizable.xcstrings, Scenes/Recovered Accounts List/RecoveredAccountsListConstructor.swift, Scenes/Recovered Accounts List/RecoveredAccountsListModel.swift, Scenes/Recovered Accounts List/RecoveredAccountsListView.swift, Scenes/Recovered Accounts List/RecoveredAccountsListViewController.swift, Scenes/Recovered Accounts List/Views/Checkbox.swift, Scenes/Recovered Accounts List/Views/FormButton.swift, Scenes/Recovered Accounts List/Views/RecoveredAccountsListCell.swift, Utils/Compatibility/SwiftUICompatibilityBaseViewController.swift, algorand.xcodeproj/project.pbxproj
- Added rescan rekeyed account functionality. It is available from the account menu and account details overlay.
- New UI components was created in SwiftUI.
- New Scene was implemented using MVVM architectural pattern.
- New files was added into the new file structure.
=> [iOS] Rekeyed Accounts - Re-scan functionality

Classes/Accounts/AccountDiscovery/SelectAddress/Screens/SelectAddressViewController.swift, Classes/Accounts/Detail/Main/Screens/AccountDetailViewController.swift, Classes/Accounts/Detail/Main/Screens/AccountInformationFlowCoordinator.swift, Classes/Demo/RescanRekeyedAccountsCoordinator.swift, Classes/Routing/Router.swift, Classes/Routing/Screen.swift, Resources/Localization/Localizable.xcstrings, Scenes/Recovered Accounts List/RecoveredAccountsListConstructor.swift, Scenes/Recovered Accounts List/RecoveredAccountsListModel.swift, Scenes/Recovered Accounts List/RecoveredAccountsListView.swift, Scenes/Recovered Accounts List/RecoveredAccountsListViewController.swift
- Added rescanning feature to the recovery flow
- Fixed issue with localized text. Not it will be presented with two lines instead showing \n between words
- Added missing confetti animation on success
=> [iOS] Rekeyed Accounts - Discover rekeyed accounts after import

Classes/Accounts/AccountDiscovery/SelectAddress/Data/SelectAddressListDataController.swift, Classes/Accounts/AccountDiscovery/SelectAddress/Screens/SelectAddressViewController.swift, Classes/Accounts/Detail/RemoveAccount/BackUpBeforeRemovingAccountWarning/BackUpBeforeRemovingAccountWarningSheet.swift, Classes/Authentication/Recover/List/Screens/AccountRecoverViewController.swift, Resources/Localization/Localizable.xcstrings, algorand.xcodeproj/project.pbxproj
- when importing accounts, if every account is already imported the finish button is enabled
- account created screen removed
- strings fixed
=> [IOS] - HD Wallet - QA Finding 17 - Account Import 

Classes/Demo/TransactionOptions/View/TransactionOptionsViewTheme.swift, algorand.xcodeproj/project.pbxproj
UI issue fixed (paddings updated)
=> BUG - UI issue on v6.0.0-12

Classes/Demo/RescanRekeyedAccountsCoordinator.swift
- Fixed the reported issue. The requests to the indexer are now split into packets of up to 50 requests each.
=> PERA-2225 - [IOS] - HD Wallet - QA Finding 24 - Importing many HD accounts at once results in an error

Classes/Application/Core/Container/TabBar/TabBarController.swift, Classes/Utils/FeatureFlag/FeatureFlag.swift
=> [iOS] Remove enable_immersve flag from code

Classes/API/Query/Accounts/Rekey/RekeyedAccountQuery.swift
- Excluded few fields from the API request when app is fetching data about the rekeyed accounts list.
=> Simplified fetching rekeyed accounts list.

Classes/Discover/DiscoverInAppBrowser/BrowserAuthorizedAddressEventHandler.swift
Fixed sending authorized accounts while on the cards flow.
=> [iOS] Update Sending Authorized Accounts for Cards

Resources/Localization/Localizable.xcstrings
=> xcstring file formatting

Classes/Accounts/List/Screens/HomeListLayout.swift, Classes/Banner/Carousel/CarouselBannerViewTheme.swift
Spot banner cell top padding increased
=> [IOS] - Padding between main banner and banner carousel needs to be adjusted 

Classes/Authentication/Common/AccountName/Screens/AccountNameSetupViewController.swift, Resources/Localization/Localizable.xcstrings, Scenes/Recovered Accounts List/RecoveredAccountsListView.swift, Scenes/Recovered Accounts List/RecoveredAccountsListViewController.swift
- Buy algo screen removed
- String fixed
=> [IOS] - Account Import via passphrase - Remove BUY ALGO screen

Classes/Accounts/List/Screens/HomeViewController.swift
Stake navigation with home button fixed
=> [iOS] TabBar disappears

Classes/Charts/Views/LineChartView.swift
Padding added to zero balance chart display
=> [iOS] 0 Balance chart display

Classes/Charts/Views/LineChartView.swift
Chart axis min and max calculated from the chart values
=> [iOS] Make Chart Axis more dynamic

Classes/Charts/Data/ChartAPIDataController.swift
Filter out watch accounts from wallet wealth balance request
=> [iOS] When you press on the chart, it looks like Watch Account values are added

Classes/Accounts/Detail/Assets/List/Screens/AccountAssetListAPIDataController.swift, Classes/Accounts/Detail/Assets/List/Screens/AccountAssetListViewController+Theme.swift, Classes/Accounts/Detail/Assets/List/Screens/AccountAssetListViewController.swift, Classes/Accounts/List/ViewModels/Main/AccountPortfolioViewModel.swift, Classes/Accounts/List/ViewModels/Main/WatchAccountPortfolioViewModel.swift, Classes/Charts/Handlers/ChartSelectedPointHandler.swift, Classes/Demo/Home/Data/HomeAPIDataController.swift, Classes/Demo/Home/Models/HomePortfolioViewModel.swift, Classes/Demo/PortfolioViewModel.swift, Classes/Routing/Router.swift, algorand.xcodeproj/project.pbxproj
- Fixed stake screen navigation from deep link
- Fixed bottom padding of the action button
- Fixed currency values for selected chart points
- Optimized code: updated chartSelectedPointViewModel
- Display values in the selected currency; applied minor fixes
=> v6.3.0 RC bugfixes.

Classes/Demo/PortfolioViewModel.swift
Fix exchange currency for charts selected point
=> [iOS] Chart balances not matching when viewing history

Classes/Application/Core/Container/TabBar/TabBarController.swift, Classes/Application/Core/Root/RootViewController.swift
Code used by the black/yellow action button (removed with the last navigation redesign) in the tab bar removed
=> TabBar Controller code cleanup

PeraWallet/Classes/Utils/Extensions/Foundation/URL/URL+Extensions.swift
Fixes an issue loading iframe based charts in the webview on vestige.fi
Closes https://algorandfoundation.atlassian.net/browse/PERA-2324
=> fix: vestige charts not loading in webview
